name: Build and test Everest on Windows
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, Windows, X64, opam-2-3]
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
